### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by akp37** [PamCatten/hot-stuff#1]
**PLEASE READ THE [CONTRIBUTING GUIDELINES](https://github.com/PamCatten/hot-stuff-kotlin/blob/main/CONTRIBUTING.md) BEFORE YOU SUBMIT**

**Describe the bug**
Attempting to edit an ITEM with the following condition causes the app to crash: ITEM has a picture attached to it from one's preexisting pictures, and the picture was deleted after the ITEM was created.

**To Reproduce**
1. Click on 'CREATE'
2. Fill in the fields
3. Click on 'SELECT PHOTO' at the bottom
4. Select the picture
5. Save item by clicking on 'SAVE ITEM'
6. Delete the chosen picture from phone
7. Return to HOT STUFF app and click on 'ITEMS'
8. Click to edit the item whose picture was deleted 
9. App crashes

**Expected behavior**
Expected to be able to edit the item regardless of the picture being deleted or not. 

**Device (please complete the following information):**
 - Device: Google Pixel 6
 - Android Version 14
 - Version 34

**Additional context**
Another condition was tested: 
Choose 'TAKE PHOTO' as opposed to 'SELECT PHOTO'. 
The ITEM can be edited despite the original photo being deleted. The app did not crash.
As for the picture that was originally attached to the ITEM, it was not there, there's just black space (for what it's worth, dark theme enabled in app).

**Comment by PamCatten** [comment]
Great find, I should have a hot fix ready for later this afternoon.

**Comment by akp37** [comment]
I tested again, along with going back to the items that were causing the app to crash, and everything is working fine. 

I like the quick message telling the user the picture is missing due to location change. It could deter users to assume that the app deleted their picture. 
The message disappears a bit quick though. Just my 2 cents. 

I would say the bug is fixed, thank you

**Comment by PamCatten** [comment]
Fantastic! I'll make a note to lengthen that message time out. Appreciate the report.
